### ISSUE TITLE
Multiple speakers 

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaNLP#10]
It happens often that multiple figures speak the same text. We need to update the data model to represent that. 

Two options:
- each utterance can carry multiple `Speaker` annotations. This has implications for the web service and R export. 
- each `Speaker` can be linked to multiple figures. This would require the type system to be changed.

**Comment by marcuswilland** [comment]
hierfür müssen wir bedenken, dass wir bei einer potentiellen ausweitung auf modernere dramen, antike dramen und auch opern es häufiger mit redenden Gruppen zu tun haben, die zw. 3 und 30 Leute groß sein kann.
-- Variante a) Chor: tritt nur als Chor auf und könnte auch nach gängiger Dramentheorie als EINE figur ausgezeichnet werden
-- Variante b) Figuren, die sonst nur alleine Reden, singen ein lied zusammen.

Ich tendiere eher zu Deiner oben genannten option 1 (each utterance can carry multiple Speaker annotations), aber das ist eine gefühlsmäßige antwort

**Comment by nilsreiter** [comment]
Guter Punkt.

Wenn der Chor Chor heißt, wird er im Moment auch schon als eine Figur gelesen.

Mir ging es hauptsächlich um die Variante b, glaube ich. Gerne auch in der Form „Alle“ …

**Comment by nilsreiter** [comment]
Done in c557649.

**Comment by nilsreiter** [comment]
We need to work on quadrama/DramaAnalysis#2
