### ISSUE TITLE
Issues in Turm parsing

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaNLP#33]
Text of 'gesang' not marked as Speech.

**Comment by nilsreiter** [comment]
This is the segment in question:

```xml
<sp>
    <speaker>
        <lb n="kha_XVI1_52_38"/>
        <hi rend="smallCaps">gesang</hi>
    </speaker>
    <p rend="blunt">
         <lb n="kha_XVI1_52_39"/>Ecce ego suscitabo super Babylonem <lb n="kha_XVI1_52_40"/>
         <fw type="lineNumber" n="40"/>quasi ventum pestilentem.</p>
</sp>
```

**Comment by gerritbruening** [comment]
Don't know if this is relevant here, but in the second version, the text of the speech is marked up as two verse lines (`l` instead of `p`).

**Comment by nilsreiter** [comment]
Both `l` and `p` are treated as character speech (at least, they should be).

**Comment by nilsreiter** [comment]
It's actually working now :)
