### ISSUE TITLE
Process Nebentext

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaNLP#38]
Export as additional table into CSV

**Comment by nilsreiter** [comment]
Export as additional table into CSV

**Comment by nilsreiter** [comment]
Just an idea for future things: some parts of the stage directions are relatively well structured and not that varied (character entering or leaving). Maybe these can be detected/parsed with a CFG framework.

**Comment by pagelj** [comment]
https://github.com/quadrama/DramaNLP/commit/eb78b739957447993753c463826a3f121cb4ff41
