### ISSUE TITLE
Include annotated coreference

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaNLP#40]
Integrate the .xmi annotations of coreference into the pipeline.
- [x] Add annotation of all mentions in addition to automatic processing of 1st person pronouns (https://github.com/quadrama/DramaNLP/commit/f264000db64c7774682c1a2995f08b587faa3bb1)
- [x] Add `mention_id` and `mention_surface` to every token of a mention (right now, it's only the first token of a mention) (https://github.com/quadrama/DramaNLP/commit/234c88531087c4ea99ff9d3e728297bf2c3803b6)
- [x] Overlapping mentions should be separated by a | (pipe) (https://github.com/quadrama/DramaNLP/pull/50/commits/303ee5c28c7146671cedb43c62ca90308d3ba3ff)
- [x] Each mention's scope is indicated by a *start* and *end* symbol -> opening bracket ( for *start* and closing bracket ) for *end* (https://github.com/quadrama/DramaNLP/commit/9386736becb9e24622e974e91563f29a2bb96f39)
- [x] Handle mentions with multiple entities (https://github.com/quadrama/DramaNLP/commit/75fbbd71f91828496336fc8ff020690271e37404)
- [x] Resolve ambiguous annotations randomly (https://github.com/quadrama/DramaNLP/commit/f9e429aec308fb4c051a8f5bd582b81c19ca0da1)
- [x] Support for handling mentions with multiple entities still needs to be added for `CastFigure` (https://github.com/quadrama/DramaNLP/commit/ebb6f427ff07af9bc91c212e352d00574f33c4c3)

**Comment by nilsreiter** [comment]
My plan was to export the annotations from XMI into TEI, and then to read them in into the pipeline. The exporting to TEI has not happened yet, though.

**Comment by pagelj** [comment]
XMI -> TEI export is now addressed in https://github.com/quadrama/DramaNLP/issues/46

**Comment by nilsreiter** [comment]
Mentions: `<rs ref="">Sara</rs>`

**Comment by nilsreiter** [comment]
Annotated disagreements: `<rs ref="e1 e2" func="or">bla</rs>`

**Comment by nilsreiter** [comment]
- If ambiguous annotations are imported: Decisions at random while importing
- Overlapping mentions are exported into `Mentionend.figure_id` column in CoNLL style

**Comment by pagelj** [comment]
Another possible value is `func="and"`, which is the default and can also be achieved by omitting `func`

**Comment by pagelj** [comment]
Aggregated mentions, i.e. mentions that point to more than one entity are simply treated as two separate entities with the same span, e.g. `they,(CATO)|(ARSENE),(cato)|(arsene)` in the `Mentioned.figure_surface` and `Mentioned.figure_id` column
