### ISSUE TITLE
xmi output cannot be generated at end of pipeline

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaNLP#42]
`--output $OUTDIR/xmi` and `--doCleanup` need to be omitted for now

**Comment by pagelj** [comment]
Seemingly related issue: https://issues.apache.org/jira/browse/UIMA-4915
could be replicated by adding the `-ea` option for the JVM

**Comment by nilsreiter** [comment]
We should probably update to a newer UIMA version anyway. The one in use is pretty old I think.

**Comment by pagelj** [comment]
Problem is a bug in UIMA. Solution is to upgrade to version >= 2.9.0SDK

**Comment by nilsreiter** [comment]
There will probably be issues with upgrading ...

**Comment by pagelj** [comment]
Yes, perhaps I'll open a new issue for that and then will try to upgrade and document the problems there
