### ISSUE TITLE
Use different tokenizer

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaNLP#71]
The current tokenizer `BreakIteratorSegmenter` does only break into sentences at certain markers (full stop, question mark, etc.). This is a problem when e.g. exporting speaker tags that often do not end with a full stop, but are separated by new lines. Using a more powerful and NLP-literate tokenizer might also help with correctly tokenizing other phenomena such as *wirds*, etc.

**Comment by pagelj** [comment]
53d6a84493f2d2914f37291442e34ecf212805b7
We are using `LanguageToolSegmenter` (for) now

**Comment by nilsreiter** [comment]
It seems `LanguageToolSegmenter` requires language info in a different format. I got the following exceptions:
```
java.lang.IllegalArgumentException: 'de' is not a language code known to LanguageTool. Supported language codes are: en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
```

Or we need to include de model into the pom file?

**Comment by nilsreiter** [comment]
Ja, man muss wohl noch 

```xml
<dependency>
	<groupId>org.languagetool</groupId>
	<artifactId>language-de</artifactId>
	<version>4.5</version>
</dependency>
```

importieren.

**Comment by pagelj** [comment]
Thanks, it didn't give me an exception, but I will include the dep into the pom anyway

**Comment by nilsreiter** [comment]
that's strange. Why didn't you get the exception? Are your texts set to German? I think it's the document language in the JCas that counts.

**Comment by nilsreiter** [comment]
(after adding the dependency, I still got the same exception ... recompiling and testing now ... )

**Comment by nilsreiter** [comment]
Better not add that now. I think the problem is somewhere else.

**Comment by nilsreiter** [comment]
Sorry, this was all a problem with dependencies not being found.
