### ISSUE TITLE
CSV file with StageDirections contains more columns than expected

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaNLP#74]
For instance, in [this file](https://github.com/quadrama/data_qd/blob/master/csv/v0fv.0.StageDirections.csv) in line 411.

It's likely connected to stage direction contained in the speech of multiple characters.

(it would be cool to fix this soon, because we need the correctly formatted files for the tutorial)

**Comment by pagelj** [comment]
Fixed in 25b2835 (release https://github.com/quadrama/DramaNLP/releases/tag/v.2.1.1)
