### ISSUE TITLE
DramaNLP on Windows

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaNLP#80]
Running DramaNLP 2.1.2 on Windows results in the following error:

`java.lang.IllegalArgumentException: 'de' is not a language code known to LanguageTool. Supported language codes are: en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.`

**Comment by pagelj** [comment]
I was able to reproduce this issue on Linux, so it is not a Windows issue. It appears to be an issue with the dependencies for DKPro's languagetool implementation. Could also be related to the issues described here : https://github.com/quadrama/DramaNLP/issues/71

When running in Eclipse it works, but not when running in a terminal...

**Comment by pagelj** [comment]
@nilsreiter Do you remember what you did to fix your issue in https://github.com/quadrama/DramaNLP/issues/71 ?

**Comment by nilsreiter** [comment]
I *think* it was a problem with caching in maven central and was solved by waiting. Maybe something like forcing to re-index?

**Comment by pagelj** [comment]
Resolved in 1270b7ac6bf9cb1b1105b2171e9fdf0bbc0f2b15
However I will still check if there are further errors on Windows

**Comment by nilsreiter** [comment]
Shouldn’t be too high on the priority list though ...

**Comment by pagelj** [comment]
After resolving the above issue, it was thankfully fine on Windows out of the box
