### ISSUE TITLE
URL Issue dkpro /develop

### ISSUE THREAD

**Issue by BenjaminKrautter** [quadrama/DramaNLP#83]
error message (goes on for other dkpro stuff with same problem):
`INFORMATION: :: loading settings :: url = jar:file:/D:/Software/DramaNLP-develop/de.unistuttgart.ims.drama.main/target/assembly/drama.Main-2.1.2.jar!/org/apache/ivy/core/settings/ivysettings.xml
Apr 06, 2020 10:18:37 AM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter error
SCHWERWIEGEND: SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.matetools-model-morphtagger-de-tiger/20121024.1/de.tudarmstadt.ukp.dkpro.core.matetools-model-morphtagger-de-tiger-20121024.1.pom`

I opened the ivysettings.xml file, could it be that `url` translates to http instead of https?
`<ivysettings>
	<settings defaultResolver="default"/>
	<include url="${ivy.default.settings.dir}/ivysettings-public.xml"/>
	<include url="${ivy.default.settings.dir}/ivysettings-shared.xml"/>
	<include url="${ivy.default.settings.dir}/ivysettings-local.xml"/>
	<include url="${ivy.default.settings.dir}/ivysettings-main-chain.xml"/>
	<include url="${ivy.default.settings.dir}/ivysettings-default-chain.xml"/>
</ivysettings>
`

**Comment by pagelj** [comment]
Could you add with which document this is occurring?

**Comment by BenjaminKrautter** [comment]
works now
